# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk

# Set the working directory in the container
WORKDIR /app

# Add the Maven wrapper and the project files
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

# Install Maven and build the application
RUN ./mvnw install

# Copy the built jar file
COPY target/ContactProfileApp-0.0.1-SNAPSHOT.jar app.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]
